version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8008:8000
    env_file:
      - app/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: intern_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - app/.env

volumes:
  postgres_data: